<?php
	define("DB_DSN", "mysql:host=localhost;dbname=sibw" );
	define("DB_USUARIO", "sibw" );
	define("DB_CONTRASENIA", "sibw" );
	define("TAMANIO_PAGINA", 5 );
	/*define("TABLA_COMENTARIO", "comentario" );
	define("TABLA_CANCION", "cancion" );*/
	define("TABLA_NOTICIA", "noticia" );
	define("TABLA_USUARIO", "usuario" );
	define("TABLA_COMENTARIO", "comentario" );
	define("TABLA_SECCION", "seccion" );
	define("TABLA_PALABRA", "palabra" );
	define("TABLA_ROL", "rol" );
	define("TABLA_PUBLICIDAD", "publicidad" );
?>
